export const games = [
  {
    id: "simple/1",
    number: 1,
    name: "Simple Crossword 1",
    date: 1542326400000,
    entries: [
      {
        id: "1-across",
        number: 1,
        humanNumber: "1",
        clue: "Taxis",
        direction: "across",
        length: 4,
        group: ["1-across"],
        position: { x: 0, y: 0 },
        separatorLocations: {},
        solution: "CABS",
      },
      {
        id: "5-across",
        number: 5,
        humanNumber: "5",
        clue: "Soccer score",
        direction: "across",
        length: 4,
        group: ["5-across"],
        position: { x: 5, y: 0 },
        separatorLocations: {},
        solution: "GOAL",
      },
      {
        id: "9-across",
        number: 9,
        humanNumber: "9",
        clue: "Canoes and Kayaks",
        direction: "across",
        length: 5,
        group: ["9-across"],
        position: { x: 10, y: 0 },
        separatorLocations: {},
        solution: "BOATS",
      },
      {
        id: "14-across",
        number: 14,
        humanNumber: "14",
        clue: "All over again",
        direction: "across",
        length: 4,
        group: ["14-across"],
        position: { x: 0, y: 1 },
        separatorLocations: {},
        solution: "ANEW",
      },
      {
        id: "15-across",
        number: 15,
        humanNumber: "15",
        clue: "Not doing anything",
        direction: "across",
        length: 4,
        group: ["15-across"],
        position: { x: 5, y: 1 },
        separatorLocations: {},
        solution: "IDLE",
      },
      {
        id: "16-across",
        number: 16,
        humanNumber: "16",
        clue: "Regions",
        direction: "across",
        length: 5,
        group: ["16-across"],
        position: { x: 10, y: 1 },
        separatorLocations: {},
        solution: "AREAS",
      },
      {
        id: "17-across",
        number: 17,
        humanNumber: "17",
        clue: "River through Egypt",
        direction: "across",
        length: 4,
        group: ["17-across"],
        position: { x: 0, y: 2 },
        separatorLocations: {},
        solution: "NILE",
      },
      {
        id: "18-across",
        number: 18,
        humanNumber: "18",
        clue: "__ Scotia, Canada",
        direction: "across",
        length: 4,
        group: ["18-across"],
        position: { x: 5, y: 2 },
        separatorLocations: {},
        solution: "NOVA",
      },
      {
        id: "19-across",
        number: 19,
        humanNumber: "19",
        clue: "Second showing on TV",
        direction: "across",
        length: 5,
        group: ["19-across"],
        position: { x: 10, y: 2 },
        separatorLocations: {},
        solution: "RERUN",
      },
      {
        id: "20-across",
        number: 20,
        humanNumber: "20",
        clue: "Spot of land in the sea",
        direction: "across",
        length: 4,
        group: ["20-across"],
        position: { x: 0, y: 3 },
        separatorLocations: {},
        solution: "ISLE",
      },
      {
        id: "21-across",
        number: 21,
        humanNumber: "21",
        clue: "Political support of regular people",
        direction: "across",
        length: 10,
        group: ["21-across"],
        position: { x: 5, y: 3 },
        separatorLocations: {},
        solution: "GRASSROOTS",
      },
      {
        id: "23-across",
        number: 23,
        humanNumber: "23",
        clue: "Acquire molars and canines",
        direction: "across",
        length: 5,
        group: ["23-across"],
        position: { x: 0, y: 4 },
        separatorLocations: {},
        solution: "TEETHE",
      },
      {
        id: "25-across",
        number: 25,
        humanNumber: "25",
        clue: "Fill in __ blank",
        direction: "across",
        length: 3,
        group: ["25-across"],
        position: { x: 8, y: 4 },
        separatorLocations: {},
        solution: "THE",
      },
      {
        id: "26-across",
        number: 26,
        humanNumber: "26",
        clue: "Makes Mistakes",
        direction: "across",
        length: 4,
        group: ["26-across"],
        position: { x: 4, y: 5 },
        separatorLocations: {},
        solution: "ERRS",
      },
      {
        id: "29-across",
        number: 29,
        humanNumber: "29",
        clue: '"Same with me!"',
        direction: "across",
        length: 6,
        group: ["29-across"],
        position: { x: 9, y: 5 },
        separatorLocations: {},
        solution: "IDOTOO",
      },
      {
        id: "34-across",
        number: 34,
        humanNumber: "34",
        clue: "Copy-machine powder",
        direction: "across",
        length: 5,
        group: ["34-across"],
        position: { x: 0, y: 6 },
        separatorLocations: {},
        solution: "TONER",
      },
      {
        id: "38-across",
        number: 38,
        humanNumber: "38",
        clue: "Organization for people 50+",
        direction: "across",
        length: 4,
        group: ["38-across"],
        position: { x: 6, y: 6 },
        separatorLocations: {},
        solution: "AARP",
      },
      {
        id: "40-across",
        number: 40,
        humanNumber: "40",
        clue: "In __ (lined up)",
        direction: "across",
        length: 4,
        group: ["40-across"],
        position: { x: 11, y: 6 },
        separatorLocations: {},
        solution: "AROW",
      },
      {
        id: "41-across",
        number: 41,
        humanNumber: "41",
        clue: "Yale or Princeton",
        direction: "across",
        length: 15,
        group: ["41-across"],
        position: { x: 0, y: 7 },
        separatorLocations: {},
        solution: "IVYLEAGUESCHOOL",
      },
      {
        id: "44-across",
        number: 44,
        humanNumber: "44",
        clue: "Weather report charts",
        direction: "across",
        length: 4,
        group: ["44-across"],
        position: { x: 0, y: 8 },
        separatorLocations: {},
        solution: "MAPS",
      },

      {
        id: "1-down",
        number: 1,
        humanNumber: "1",
        clue: '"Be Quiet!"',
        direction: "down",
        length: 5,
        group: ["1-down"],
        position: { x: 0, y: 0 },
        separatorLocations: {},
        solution: "CANIT",
      },
      {
        id: "2-down",
        number: 2,
        humanNumber: "2",
        clue: "Licorice-flavored herb",
        direction: "down",
        length: 5,
        group: ["2-down"],
        position: { x: 1, y: 0 },
        separatorLocations: {},
        solution: "ANISE",
      },
      {
        id: "3-down",
        number: 3,
        humanNumber: "3",
        clue: "Charming Southern woman",
        direction: "down",
        length: 5,
        group: ["3-down"],
        position: { x: 2, y: 0 },
        separatorLocations: {},
        solution: "BELLE",
      },
      {
        id: "4-down",
        number: 4,
        humanNumber: "4",
        clue: "Sugary",
        direction: "down",
        length: 5,
        group: ["4-down"],
        position: { x: 3, y: 0 },
        separatorLocations: {},
        solution: "SWEET",
      },
      {
        id: "5-down",
        number: 5,
        humanNumber: "5",
        clue: "__ snap (type of cookie)",
        direction: "down",
        length: 6,
        group: ["5-down"],
        position: { x: 5, y: 0 },
        separatorLocations: {},
        solution: "GINGER",
      },
    ],
    solutionAvailable: true,
    dateSolutionAvailable: 1542326400000,
    dimensions: {
      cols: 15,
      rows: 15,
    },
    crosswordType: "quick",
  },
];
