export const games = [
  {
    id: "simple/1",
    number: 1,
    name: "Simple Crossword 1",
    date: 1542326400000,
    entries: [
      {
        id: "1-across",
        number: 1,
        humanNumber: "1",
        clue: "Taxis",
        direction: "across",
        length: 4,
        group: ["1-across"],
        position: { x: 0, y: 0 },
        separatorLocations: {},
        solution: "CABS",
      },
      {
        id: "5-across",
        number: 5,
        humanNumber: "5",
        clue: "Soccer score",
        direction: "across",
        length: 4,
        group: ["5-across"],
        position: { x: 5, y: 0 },
        separatorLocations: {},
        solution: "GOAL",
      },
      {
        id: "9-across",
        number: 9,
        humanNumber: "9",
        clue: "Canoes and Kayaks",
        direction: "across",
        length: 5,
        group: ["9-across"],
        position: { x: 10, y: 0 },
        separatorLocations: {},
        solution: "BOATS",
      },
      {
        id: "14-across",
        number: 14,
        humanNumber: "14",
        clue: "All over again",
        direction: "across",
        length: 4,
        group: ["14-across"],
        position: { x: 0, y: 1 },
        separatorLocations: {},
        solution: "ANEW",
      },
      {
        id: "15-across",
        number: 15,
        humanNumber: "15",
        clue: "Not doing anything",
        direction: "across",
        length: 4,
        group: ["15-across"],
        position: { x: 5, y: 1 },
        separatorLocations: {},
        solution: "IDLE",
      },
      {
        id: "16-across",
        number: 16,
        humanNumber: "16",
        clue: "Regions",
        direction: "across",
        length: 5,
        group: ["16-across"],
        position: { x: 10, y: 1 },
        separatorLocations: {},
        solution: "AREAS",
      },
      {
        id: "17-across",
        number: 17,
        humanNumber: "17",
        clue: "River through Egypt",
        direction: "across",
        length: 4,
        group: ["17-across"],
        position: { x: 0, y: 2 },
        separatorLocations: {},
        solution: "NILE",
      },

      {
        id: "1-down",
        number: 1,
        humanNumber: "1",
        clue: '"Be Quiet!"',
        direction: "down",
        length: 5,
        group: ["1-down"],
        position: { x: 0, y: 0 },
        separatorLocations: {},
        solution: "CANIT",
      },
      {
        id: "2-down",
        number: 2,
        humanNumber: "2",
        clue: "Licorice-flavored herb",
        direction: "down",
        length: 5,
        group: ["2-down"],
        position: { x: 1, y: 0 },
        separatorLocations: {},
        solution: "ANISE",
      },
      {
        id: "3-down",
        number: 3,
        humanNumber: "3",
        clue: "Charming Southern woman",
        direction: "down",
        length: 5,
        group: ["3-down"],
        position: { x: 2, y: 0 },
        separatorLocations: {},
        solution: "BELLE",
      },
      {
        id: "4-down",
        number: 4,
        humanNumber: "4",
        clue: "Sugary",
        direction: "down",
        length: 5,
        group: ["4-down"],
        position: { x: 3, y: 0 },
        separatorLocations: {},
        solution: "SWEET",
      },
      {
        id: "5-down",
        number: 5,
        humanNumber: "5",
        clue: "_ snap (type of cookie)",
        direction: "down",
        length: 6,
        group: ["5-down"],
        position: { x: 5, y: 0 },
        separatorLocations: {},
        solution: "GINGER",
      },
    ],
    solutionAvailable: true,
    dateSolutionAvailable: 1542326400000,
    dimensions: {
      cols: 15,
      rows: 15,
    },
    crosswordType: "quick",
  },
];
