export const games = [
  {
    id: "simple/1",
    number: 1,
    name: "Simple Crossword 1",
    date: 1542326400000,
    entries: [
      {
        id: "1-across",
        number: 1,
        humanNumber: "1",
        clue: "Taxis",
        direction: "across",
        length: 4,
        group: ["1-across"],
        position: { x: 0, y: 0 },
        separatorLocations: {},
        solution: "CABS",
      },
      {
        id: "5-across",
        number: 5,
        humanNumber: "5",
        clue: "Soccer score",
        direction: "across",
        length: 4,
        group: ["5-across"],
        position: { x: 5, y: 0 },
        separatorLocations: {},
        solution: "GOAL",
      },
      {
        id: "9-across",
        number: 9,
        humanNumber: "9",
        clue: "Canoes and Kayaks",
        direction: "across",
        length: 5,
        group: ["9-across"],
        position: { x: 10, y: 0 },
        separatorLocations: {},
        solution: "BOATS",
      },
      {
        id: "14-across",
        number: 14,
        humanNumber: "14",
        clue: "All over again",
        direction: "across",
        length: 4,
        group: ["14-across"],
        position: { x: 0, y: 1 },
        separatorLocations: {},
        solution: "ANEW",
      },

      {
        id: "1-down",
        number: 1,
        humanNumber: "1",
        clue: "Colour (6)",
        direction: "down",
        length: 6,
        group: ["1-down"],
        position: { x: 0, y: 0 },
        separatorLocations: {},
        solution: "YELLOW",
      },
      {
        id: "3-down",
        number: 3,
        humanNumber: "3",
        clue: "Bits and bobs (4,3,4)",
        direction: "down",
        length: 7,
        group: ["3-down"],
        position: { x: 3, y: 0 },
        separatorLocations: {},
        solution: "ODDSAND",
      },
      {
        id: "4-down",
        number: 4,
        humanNumber: "4",
        clue: "See 3 down",
        direction: "down",
        length: 4,
        group: ["4-down"],
        position: { x: 6, y: 1 },
        separatorLocations: {},
        solution: "ENDS",
      },
    ],
    solutionAvailable: true,
    dateSolutionAvailable: 1542326400000,
    dimensions: {
      cols: 15,
      rows: 15,
    },
    crosswordType: "quick",
  },
];
