export const mockLicenses = [
  {
    key: "react-paginate@7.1.3",
    name: "react-paginate",
    image: "http://github.com/AdeleD.png",
    userUrl: "http://github.com/AdeleD",
    username: "AdeleD",
    licenses: "MIT",
    version: "7.1.3",
    repository: "https://github.com/AdeleD/react-paginate",
    licenseUrl: "https://github.com/AdeleD/react-paginate/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "bonzo@2.0.0",
    name: "bonzo",
    image: "http://github.com/Ded.png",
    userUrl: "http://github.com/Ded",
    username: "Ded",
    licenses: "MIT*",
    version: "2.0.0",
    repository: "https://github.com/ded/bonzo",
    licenseUrl: "https://github.com/ded/bonzo/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "qwery@4.0.0",
    name: "qwery",
    image: "http://github.com/Ded.png",
    userUrl: "http://github.com/Ded",
    username: "Ded",
    licenses: "UNKNOWN",
    version: "4.0.0",
    repository: "https://github.com/ded/qwery",
    licenseUrl: "https://github.com/ded/qwery/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "underscore.string@3.3.5",
    name: "underscore.string",
    image: "http://github.com/Epeli.png",
    userUrl: "http://github.com/Epeli",
    username: "Epeli",
    licenses: "MIT",
    version: "3.3.5",
    repository: "https://github.com/epeli/underscore.string",
    licenseUrl: "https://github.com/epeli/underscore.string",
    parents: "the-bedtime-project",
  },
  {
    key: "react-dom@17.0.2",
    name: "react-dom",
    image: "http://github.com/Facebook.png",
    userUrl: "http://github.com/Facebook",
    username: "Facebook",
    licenses: "MIT",
    version: "17.0.2",
    repository: "https://github.com/facebook/react",
    licenseUrl: "https://github.com/facebook/react/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "react-scripts@4.0.3",
    name: "react-scripts",
    image: "http://github.com/Facebook.png",
    userUrl: "http://github.com/Facebook",
    username: "Facebook",
    licenses: "MIT",
    version: "4.0.3",
    repository: "https://github.com/facebook/create-react-app",
    licenseUrl:
      "https://github.com/facebook/create-react-app/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "react@17.0.2",
    name: "react",
    image: "http://github.com/Facebook.png",
    userUrl: "http://github.com/Facebook",
    username: "Facebook",
    licenses: "MIT",
    version: "17.0.2",
    repository: "https://github.com/facebook/react",
    licenseUrl: "https://github.com/facebook/react/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "bean@1.0.15",
    name: "bean",
    image: "http://github.com/Fat.png",
    userUrl: "http://github.com/Fat",
    username: "Fat",
    licenses: "MIT*",
    version: "1.0.15",
    repository: "https://github.com/fat/bean",
    licenseUrl: "https://github.com/fat/bean/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "web-vitals@1.1.2",
    name: "web-vitals",
    image: "http://github.com/GoogleChrome.png",
    userUrl: "http://github.com/GoogleChrome",
    username: "GoogleChrome",
    licenses: "Apache-2.0",
    version: "1.1.2",
    repository: "https://github.com/GoogleChrome/web-vitals",
    licenseUrl: "https://github.com/GoogleChrome/web-vitals/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "react-crossword@0.2.3",
    name: "react-crossword",
    image: "http://github.com/Guardian.png",
    userUrl: "http://github.com/Guardian",
    username: "Guardian",
    licenses: "Apache-2.0",
    version: "0.2.3",
    repository: "https://github.com/guardian/react-crossword",
    licenseUrl:
      "https://raw.githubusercontent.com/guardian/react-crossword/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "underscore@1.13.1",
    name: "underscore",
    image: "http://github.com/Jashkenas.png",
    userUrl: "http://github.com/Jashkenas",
    username: "Jashkenas",
    licenses: "MIT",
    version: "1.13.1",
    repository: "https://github.com/jashkenas/underscore",
    licenseUrl: "https://github.com/jashkenas/underscore/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "react-helmet@6.1.0",
    name: "react-helmet",
    image: "http://github.com/Nfl.png",
    userUrl: "http://github.com/Nfl",
    username: "Nfl",
    licenses: "MIT",
    version: "6.1.0",
    repository: "https://github.com/nfl/react-helmet",
    licenseUrl: "https://github.com/nfl/react-helmet/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "wolfy87-eventemitter@5.2.9",
    name: "wolfy87-eventemitter",
    image: "http://github.com/Olical.png",
    userUrl: "http://github.com/Olical",
    username: "Olical",
    licenses: "Unlicense",
    version: "5.2.9",
    repository: "https://github.com/Olical/EventEmitter",
    licenseUrl: "https://github.com/Olical/EventEmitter/raw/master/UNLICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "react-router-dom@5.2.0",
    name: "react-router-dom",
    image: "http://github.com/ReactTraining.png",
    userUrl: "http://github.com/ReactTraining",
    username: "ReactTraining",
    licenses: "MIT",
    version: "5.2.0",
    repository: "https://github.com/ReactTraining/react-router",
    licenseUrl:
      "https://github.com/ReactTraining/react-router/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "react-markdown@6.0.2",
    name: "react-markdown",
    image: "http://github.com/Remarkjs.png",
    userUrl: "http://github.com/Remarkjs",
    username: "Remarkjs",
    licenses: "MIT",
    version: "6.0.2",
    repository: "https://github.com/remarkjs/react-markdown",
    licenseUrl: "https://github.com/remarkjs/react-markdown/raw/master/license",
    parents: "the-bedtime-project",
  },
  {
    key: "sass-mq@5.0.1",
    name: "sass-mq",
    image: "http://github.com/Sass.png",
    userUrl: "http://github.com/Sass",
    username: "Sass",
    licenses: "MIT",
    version: "5.0.1",
    repository: "https://github.com/sass-mq/sass-mq",
    licenseUrl: "https://github.com/sass-mq/sass-mq/raw/master/LICENSE.md",
    parents: "the-bedtime-project",
  },
  {
    key: "sass@1.35.1",
    name: "sass",
    image: "http://github.com/Sass.png",
    userUrl: "http://github.com/Sass",
    username: "Sass",
    licenses: "MIT",
    version: "1.35.1",
    repository: "https://github.com/sass/dart-sass",
    licenseUrl: "https://github.com/sass/dart-sass/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "gh-pages@3.1.0",
    name: "gh-pages",
    image: "http://github.com/Tschaub.png",
    userUrl: "http://github.com/Tschaub",
    username: "Tschaub",
    licenses: "MIT",
    version: "3.1.0",
    repository: "https://github.com/tschaub/gh-pages",
    licenseUrl: "https://github.com/tschaub/gh-pages/raw/master/LICENSE",
    parents: "the-bedtime-project",
  },
  {
    key: "fastdom@1.0.10",
    name: "fastdom",
    image: "http://github.com/Wilsonpage.png",
    userUrl: "http://github.com/Wilsonpage",
    username: "Wilsonpage",
    licenses: "MIT",
    version: "1.0.10",
    repository: "https://github.com/wilsonpage/fastdom",
    licenseUrl: "https://github.com/wilsonpage/fastdom",
    parents: "the-bedtime-project",
  },
];
