export const GrowingGreen = {
  id: "simple/1",
  author: "Gail Grabowski, edited by Stanley Newman",
  number: 1,
  name: "Growing Green",
  date: 1542326400000,
  solutionAvailable: true,
  dateSolutionAvailable: 1542326400000,
  dimensions: {
    cols: 15,
    rows: 15,
  },
  crosswordType: "quick",
  entries: [
    {
      id: "1-across",
      number: 1,
      humanNumber: "1",
      clue: "Taxis",
      direction: "across",
      length: 4,
      group: ["1-across"],
      position: { x: 0, y: 0 },
      separatorLocations: {},
      solution: "CABS",
    },
    {
      id: "5-across",
      number: 5,
      humanNumber: "5",
      clue: "Soccer score",
      direction: "across",
      length: 4,
      group: ["5-across"],
      position: { x: 5, y: 0 },
      separatorLocations: {},
      solution: "GOAL",
    },
    {
      id: "9-across",
      number: 9,
      humanNumber: "9",
      clue: "Canoes and Kayaks",
      direction: "across",
      length: 5,
      group: ["9-across"],
      position: { x: 10, y: 0 },
      separatorLocations: {},
      solution: "BOATS",
    },
    {
      id: "14-across",
      number: 14,
      humanNumber: "14",
      clue: "All over again",
      direction: "across",
      length: 4,
      group: ["14-across"],
      position: { x: 0, y: 1 },
      separatorLocations: {},
      solution: "ANEW",
    },
    {
      id: "15-across",
      number: 15,
      humanNumber: "15",
      clue: "Not doing anything",
      direction: "across",
      length: 4,
      group: ["15-across"],
      position: { x: 5, y: 1 },
      separatorLocations: {},
      solution: "IDLE",
    },
    {
      id: "16-across",
      number: 16,
      humanNumber: "16",
      clue: "Regions",
      direction: "across",
      length: 5,
      group: ["16-across"],
      position: { x: 10, y: 1 },
      separatorLocations: {},
      solution: "AREAS",
    },
    {
      id: "17-across",
      number: 17,
      humanNumber: "17",
      clue: "River through Egypt",
      direction: "across",
      length: 4,
      group: ["17-across"],
      position: { x: 0, y: 2 },
      separatorLocations: {},
      solution: "NILE",
    },
    {
      id: "18-across",
      number: 18,
      humanNumber: "18",
      clue: "__ Scotia, Canada",
      direction: "across",
      length: 4,
      group: ["18-across"],
      position: { x: 5, y: 2 },
      separatorLocations: {},
      solution: "NOVA",
    },
    {
      id: "19-across",
      number: 19,
      humanNumber: "19",
      clue: "Second showing on TV",
      direction: "across",
      length: 5,
      group: ["19-across"],
      position: { x: 10, y: 2 },
      separatorLocations: {},
      solution: "RERUN",
    },
    {
      id: "20-across",
      number: 20,
      humanNumber: "20",
      clue: "Spot of land in the sea",
      direction: "across",
      length: 4,
      group: ["20-across"],
      position: { x: 0, y: 3 },
      separatorLocations: {},
      solution: "ISLE",
    },
    {
      id: "21-across",
      number: 21,
      humanNumber: "21",
      clue: "Political support of regular people",
      direction: "across",
      length: 10,
      group: ["21-across"],
      position: { x: 5, y: 3 },
      separatorLocations: {},
      solution: "GRASSROOTS",
    },
    {
      id: "23-across",
      number: 23,
      humanNumber: "23",
      clue: "Acquire molars and canines",
      direction: "across",
      length: 6,
      group: ["23-across"],
      position: { x: 0, y: 4 },
      separatorLocations: {},
      solution: "TEETHE",
    },
    {
      id: "25-across",
      number: 25,
      humanNumber: "25",
      clue: "Fill in __ blank",
      direction: "across",
      length: 3,
      group: ["25-across"],
      position: { x: 8, y: 4 },
      separatorLocations: {},
      solution: "THE",
    },
    {
      id: "26-across",
      number: 26,
      humanNumber: "26",
      clue: "Makes Mistakes",
      direction: "across",
      length: 4,
      group: ["26-across"],
      position: { x: 4, y: 5 },
      separatorLocations: {},
      solution: "ERRS",
    },
    {
      id: "29-across",
      number: 29,
      humanNumber: "29",
      clue: '"Same with me!"',
      direction: "across",
      length: 6,
      group: ["29-across"],
      position: { x: 9, y: 5 },
      separatorLocations: {},
      solution: "IDOTOO",
    },
    {
      id: "34-across",
      number: 34,
      humanNumber: "34",
      clue: "Copy-machine powder",
      direction: "across",
      length: 5,
      group: ["34-across"],
      position: { x: 0, y: 6 },
      separatorLocations: {},
      solution: "TONER",
    },
    {
      id: "38-across",
      number: 38,
      humanNumber: "38",
      clue: "Organization for people 50+",
      direction: "across",
      length: 4,
      group: ["38-across"],
      position: { x: 6, y: 6 },
      separatorLocations: {},
      solution: "AARP",
    },
    {
      id: "40-across",
      number: 40,
      humanNumber: "40",
      clue: "In __ (lined up)",
      direction: "across",
      length: 4,
      group: ["40-across"],
      position: { x: 11, y: 6 },
      separatorLocations: {},
      solution: "AROW",
    },
    {
      id: "41-across",
      number: 41,
      humanNumber: "41",
      clue: "Yale or Princeton",
      direction: "across",
      length: 15,
      group: ["41-across"],
      position: { x: 0, y: 7 },
      separatorLocations: {},
      solution: "IVYLEAGUESCHOOL",
    },
    {
      id: "44-across",
      number: 44,
      humanNumber: "44",
      clue: "Weather report charts",
      direction: "across",
      length: 4,
      group: ["44-across"],
      position: { x: 0, y: 8 },
      separatorLocations: {},
      solution: "MAPS",
    },
    {
      id: "45-across",
      number: 45,
      humanNumber: "45",
      clue: "Look after",
      direction: "across",
      length: 4,
      group: ["45-across"],
      position: { x: 5, y: 8 },
      separatorLocations: {},
      solution: "TEND",
    },
    {
      id: "46-across",
      number: 46,
      humanNumber: "46",
      clue: "Coupes and convertibles",
      direction: "across",
      length: 5,
      group: ["46-across"],
      position: { x: 10, y: 8 },
      separatorLocations: {},
      solution: "AUTOS",
    },
    {
      id: "47-across",
      number: 47,
      humanNumber: "47",
      clue: "Firstborn child",
      direction: "across",
      length: 6,
      group: ["47-across"],
      position: { x: 0, y: 9 },
      separatorLocations: {},
      solution: "ELDEST",
    },
    {
      id: "49-across",
      number: 49,
      humanNumber: "49",
      clue: "Right away, in memos",
      direction: "across",
      length: 4,
      group: ["49-across"],
      position: { x: 7, y: 9 },
      separatorLocations: {},
      solution: "ASAP",
    },
    {
      id: "51-across",
      number: 51,
      humanNumber: "51",
      clue: "That man's",
      direction: "across",
      length: 3,
      group: ["51-across"],
      position: { x: 4, y: 10 },
      separatorLocations: {},
      solution: "HIS",
    },
    {
      id: "53-across",
      number: 53,
      humanNumber: "53",
      clue: "Sight and smell",
      direction: "across",
      length: 6,
      group: ["53-across"],
      position: { x: 9, y: 10 },
      separatorLocations: {},
      solution: "SENSES",
    },
    {
      id: "58-across",
      number: 58,
      humanNumber: "58",
      clue: "Sailors' short coats",
      direction: "across",
      length: 10,
      group: ["58-across"],
      position: { x: 0, y: 11 },
      separatorLocations: {},
      solution: "PEAJACKETS",
    },
    {
      id: "64-across",
      number: 64,
      humanNumber: "64",
      clue: "Unwrap, as a gift",
      direction: "across",
      length: 4,
      group: ["64-across"],
      position: { x: 11, y: 11 },
      separatorLocations: {},
      solution: "OPEN",
    },
    {
      id: "65-across",
      number: 65,
      humanNumber: "65",
      clue: "Misbehave",
      direction: "across",
      length: 5,
      group: ["65-across"],
      position: { x: 0, y: 12 },
      separatorLocations: {},
      solution: "ACTUP",
    },
    {
      id: "66-across",
      number: 66,
      humanNumber: "66",
      clue: "Sudden impulse",
      direction: "across",
      length: 4,
      group: ["66-across"],
      position: { x: 6, y: 12 },
      separatorLocations: {},
      solution: "URGE",
    },
    {
      id: "67-across",
      number: 67,
      humanNumber: "67",
      clue: "Bike's wheel",
      direction: "across",
      length: 4,
      group: ["67-across"],
      position: { x: 11, y: 12 },
      separatorLocations: {},
      solution: "TIRE",
    },
    {
      id: "68-across",
      number: 68,
      humanNumber: "68",
      clue: "Lamp covering",
      direction: "across",
      length: 5,
      group: ["68-across"],
      position: { x: 0, y: 13 },
      separatorLocations: {},
      solution: "SHADE",
    },
    {
      id: "69-across",
      number: 69,
      humanNumber: "69",
      clue: '"Tender" beef cut',
      direction: "across",
      length: 4,
      group: ["69-across"],
      position: { x: 6, y: 13 },
      separatorLocations: {},
      solution: "LOIN",
    },
    {
      id: "70-across",
      number: 70,
      humanNumber: "70",
      clue: "One of the Great Lakes",
      direction: "across",
      length: 4,
      group: ["70-across"],
      position: { x: 11, y: 13 },
      separatorLocations: {},
      solution: "ERIE",
    },
    {
      id: "71-across",
      number: 71,
      humanNumber: "71",
      clue: "Commotions",
      direction: "across",
      length: 5,
      group: ["71-across"],
      position: { x: 0, y: 14 },
      separatorLocations: {},
      solution: "TODOS",
    },
    {
      id: "72-across",
      number: 72,
      humanNumber: "72",
      clue: "Barn's upper level",
      direction: "across",
      length: 4,
      group: ["72-across"],
      position: { x: 6, y: 14 },
      separatorLocations: {},
      solution: "LOFT",
    },
    {
      id: "73-across",
      number: 73,
      humanNumber: "73",
      clue: "Fortune teller",
      direction: "across",
      length: 4,
      group: ["73-across"],
      position: { x: 11, y: 14 },
      separatorLocations: {},
      solution: "SEER",
    },

    // DOWN

    {
      id: "1-down",
      number: 1,
      humanNumber: "1",
      clue: '"Be Quiet!"',
      direction: "down",
      length: 5,
      group: ["1-down"],
      position: { x: 0, y: 0 },
      separatorLocations: {},
      solution: "CANIT",
    },
    {
      id: "2-down",
      number: 2,
      humanNumber: "2",
      clue: "Licorice-flavored herb",
      direction: "down",
      length: 5,
      group: ["2-down"],
      position: { x: 1, y: 0 },
      separatorLocations: {},
      solution: "ANISE",
    },
    {
      id: "3-down",
      number: 3,
      humanNumber: "3",
      clue: "Charming Southern woman",
      direction: "down",
      length: 5,
      group: ["3-down"],
      position: { x: 2, y: 0 },
      separatorLocations: {},
      solution: "BELLE",
    },
    {
      id: "4-down",
      number: 4,
      humanNumber: "4",
      clue: "Sugary",
      direction: "down",
      length: 5,
      group: ["4-down"],
      position: { x: 3, y: 0 },
      separatorLocations: {},
      solution: "SWEET",
    },
    {
      id: "5-down",
      number: 5,
      humanNumber: "5",
      clue: "__ snap (type of cookie)",
      direction: "down",
      length: 6,
      group: ["5-down"],
      position: { x: 5, y: 0 },
      separatorLocations: {},
      solution: "GINGER",
    },
    {
      id: "6-down",
      number: 6,
      humanNumber: "6",
      clue: "Scent",
      direction: "down",
      length: 4,
      group: ["6-down"],
      position: { x: 6, y: 0 },
      separatorLocations: {},
      solution: "ODOR",
    },
    {
      id: "7-down",
      number: 7,
      humanNumber: "7",
      clue: "Thomas __ Edison",
      direction: "down",
      length: 4,
      group: ["7-down"],
      position: { x: 7, y: 0 },
      separatorLocations: {},
      solution: "ALVA",
    },
    {
      id: "8-down",
      number: 8,
      humanNumber: "8",
      clue: "Minimum amount",
      direction: "down",
      length: 5,
      group: ["8-down"],
      position: { x: 8, y: 0 },
      separatorLocations: {},
      solution: "LEAST",
    },
    {
      id: "9-down",
      number: 9,
      humanNumber: "9",
      clue: "Kept from entering",
      direction: "down",
      length: 6,
      group: ["9-down"],
      position: { x: 10, y: 0 },
      separatorLocations: {},
      solution: "BARRED",
    },
    {
      id: "10-down",
      number: 10,
      humanNumber: "10",
      clue: "Black-and-white cookie",
      direction: "down",
      length: 4,
      group: ["10-down"],
      position: { x: 11, y: 0 },
      separatorLocations: {},
      solution: "OREO",
    },
    {
      id: "11-down",
      number: 11,
      humanNumber: "11",
      clue: "Aviation-related prefix",
      direction: "down",
      length: 4,
      group: ["11-down"],
      position: { x: 12, y: 0 },
      separatorLocations: {},
      solution: "AERO",
    },
    {
      id: "12-down",
      number: 12,
      humanNumber: "12",
      clue: "Tightly stretched",
      direction: "down",
      length: 4,
      group: ["12-down"],
      position: { x: 13, y: 0 },
      separatorLocations: {},
      solution: "TAUT",
    },
    {
      id: "13-down",
      number: 13,
      humanNumber: "13",
      clue: "Tax form IDs",
      direction: "down",
      length: 4,
      group: ["13-down"],
      position: { x: 14, y: 0 },
      separatorLocations: {},
      solution: "SSNS",
    },
    {
      id: "22-down",
      number: 22,
      humanNumber: "22",
      clue: "Ocean vessels",
      direction: "down",
      length: 5,
      group: ["22-down"],
      position: { x: 9, y: 3 },
      separatorLocations: {},
      solution: "SHIPS",
    },
    {
      id: "24-down",
      number: 24,
      humanNumber: "24",
      clue: "Roll-call response",
      direction: "down",
      length: 4,
      group: ["24-down"],
      position: { x: 4, y: 4 },
      separatorLocations: {},
      solution: "HERE",
    },
    {
      id: "27-down",
      number: 27,
      humanNumber: "27",
      clue: "Intense anger",
      direction: "down",
      length: 4,
      group: ["27-down"],
      position: { x: 6, y: 5 },
      separatorLocations: {},
      solution: "RAGE",
    },
    {
      id: "28-down",
      number: 28,
      humanNumber: "28",
      clue: "Steam room",
      direction: "down",
      length: 5,
      group: ["28-down"],
      position: { x: 7, y: 5 },
      separatorLocations: {},
      solution: "SAUNA",
    },
    {
      id: "30-down",
      number: 30,
      humanNumber: "30",
      clue: "Honolulu's island",
      direction: "down",
      length: 4,
      group: ["30-down"],
      position: { x: 11, y: 5 },
      separatorLocations: {},
      solution: "OAHU",
    },
    {
      id: "31-down",
      number: 31,
      humanNumber: "31",
      clue: "Jogger's pace",
      direction: "down",
      length: 4,
      group: ["31-down"],
      position: { x: 12, y: 5 },
      separatorLocations: {},
      solution: "TROT",
    },
    {
      id: "32-down",
      number: 32,
      humanNumber: "32",
      clue: "Trip odometer's initial reading",
      direction: "down",
      length: 4,
      group: ["32-down"],
      position: { x: 13, y: 5 },
      separatorLocations: {},
      solution: "OOOO",
    },
    {
      id: "33-down",
      number: 33,
      humanNumber: "33",
      clue: '"Wise" birds',
      direction: "down",
      length: 4,
      group: ["33-down"],
      position: { x: 14, y: 5 },
      separatorLocations: {},
      solution: "OWLS",
    },
    {
      id: "34-down",
      number: 34,
      humanNumber: "34",
      clue: "Clock reading",
      direction: "down",
      length: 4,
      group: ["34-down"],
      position: { x: 0, y: 6 },
      separatorLocations: {},
      solution: "TIME",
    },
    {
      id: "35-down",
      number: 35,
      humanNumber: "35",
      clue: "Shape of an egg",
      direction: "down",
      length: 4,
      group: ["35-down"],
      position: { x: 1, y: 6 },
      separatorLocations: {},
      solution: "OVAL",
    },
    {
      id: "36-down",
      number: 36,
      humanNumber: "36",
      clue: "Big Apple cops' org.",
      direction: "down",
      length: 4,
      group: ["36-down"],
      position: { x: 2, y: 6 },
      separatorLocations: {},
      solution: "NYPD",
    },
    {
      id: "37-down",
      number: 37,
      humanNumber: "37",
      clue: "Otherwise",
      direction: "down",
      length: 4,
      group: ["37-down"],
      position: { x: 3, y: 6 },
      separatorLocations: {},
      solution: "ELSE",
    },
    {
      id: "39-down",
      number: 39,
      humanNumber: "39",
      clue: "Crimson and scarlet",
      direction: "down",
      length: 4,
      group: ["39-down"],
      position: { x: 8, y: 6 },
      separatorLocations: {},
      solution: "REDS",
    },
    {
      id: "42-down",
      number: 42,
      humanNumber: "42",
      clue: "Home's upper storage area",
      direction: "down",
      length: 5,
      group: ["42-down"],
      position: { x: 5, y: 7 },
      separatorLocations: {},
      solution: "ATTIC",
    },
    {
      id: "43-down",
      number: 43,
      humanNumber: "43",
      clue: " __ Cod, MA",
      direction: "down",
      length: 4,
      group: ["43-down"],
      position: { x: 10, y: 7 },
      separatorLocations: {},
      solution: "CAPE",
    },
    {
      id: "48-down",
      number: 48,
      humanNumber: "48",
      clue: "Circles and triangles",
      direction: "down",
      length: 6,
      group: ["48-down"],
      position: { x: 4, y: 9 },
      separatorLocations: {},
      solution: "SHAPES",
    },
    {
      id: "50-down",
      number: 50,
      humanNumber: "50",
      clue: "Agree (to)",
      direction: "down",
      length: 6,
      group: ["50-down"],
      position: { x: 9, y: 9 },
      separatorLocations: {},
      solution: "ASSENT",
    },
    {
      id: "52-down",
      number: 52,
      humanNumber: "52",
      clue: "__ and crossbones (pirate flag)",
      direction: "down",
      length: 5,
      group: ["52-down"],
      position: { x: 6, y: 10 },
      separatorLocations: {},
      solution: "SKULL",
    },
    {
      id: "54-down",
      number: 54,
      humanNumber: "54",
      clue: "Brief memos",
      direction: "down",
      length: 5,
      group: ["54-down"],
      position: { x: 11, y: 10 },
      separatorLocations: {},
      solution: "NOTES",
    },
    {
      id: "55-down",
      number: 55,
      humanNumber: "55",
      clue: "Church steeple",
      direction: "down",
      length: 5,
      group: ["55-down"],
      position: { x: 12, y: 10 },
      separatorLocations: {},
      solution: "SPIRE",
    },
    {
      id: "56-down",
      number: 56,
      humanNumber: "56",
      clue: "Spooky",
      direction: "down",
      length: 5,
      group: ["56-down"],
      position: { x: 13, y: 10 },
      separatorLocations: {},
      solution: "EERIE",
    },
    {
      id: "57-down",
      number: 57,
      humanNumber: "57",
      clue: "Scornful expression",
      direction: "down",
      length: 5,
      group: ["57-down"],
      position: { x: 14, y: 10 },
      separatorLocations: {},
      solution: "SNEER",
    },
    {
      id: "58-down",
      number: 58,
      humanNumber: "58",
      clue: "In the __ (long ago)",
      direction: "down",
      length: 4,
      group: ["58-down"],
      position: { x: 0, y: 11 },
      separatorLocations: {},
      solution: "PAST",
    },
    {
      id: "59-down",
      number: 59,
      humanNumber: "59",
      clue: "Canyon sound",
      direction: "down",
      length: 4,
      group: ["59-down"],
      position: { x: 1, y: 11 },
      separatorLocations: {},
      solution: "ECHO",
    },
    {
      id: "60-down",
      number: 60,
      humanNumber: "60",
      clue: "Just slightly",
      direction: "down",
      length: 4,
      group: ["60-down"],
      position: { x: 2, y: 11 },
      separatorLocations: {},
      solution: "ATAD",
    },
    {
      id: "61-down",
      number: 61,
      humanNumber: "61",
      clue: "Japanese martial art",
      direction: "down",
      length: 4,
      group: ["61-down"],
      position: { x: 3, y: 11 },
      separatorLocations: {},
      solution: "JUDO",
    },
    {
      id: "62-down",
      number: 62,
      humanNumber: "62",
      clue: "Slangy suffix for switch",
      direction: "down",
      length: 4,
      group: ["62-down"],
      position: { x: 7, y: 11 },
      separatorLocations: {},
      solution: "EROO",
    },
    {
      id: "63-down",
      number: 63,
      humanNumber: "63",
      clue: "Employee's end-of-week shout",
      direction: "down",
      length: 4,
      group: ["63-down"],
      position: { x: 8, y: 11 },
      separatorLocations: {},
      solution: "TGIF",
    },
  ],
};
